# Generated by Django 5.0.6 on 2024-06-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myapplyjoblist',
            old_name='dataYouApply',
            new_name='dateYouApply',
        ),
    ]
