# Generated by Django 5.0.6 on 2024-06-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_rename_datayouapply_myapplyjoblist_dateyouapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issortlist',
            name='dateYouApply',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='myapplyjoblist',
            name='dateYouApply',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
