# Generated by Django 5.0.6 on 2024-06-30 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_issortlist_dateyouapply_and_more'),
        ('hr', '0002_remove_candidateapplication_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapplyjoblist',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.candidateapplications'),
        ),
    ]
