# Generated by Django 5.0.6 on 2024-07-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GenerateImage',
            new_name='GeneratedImage',
        ),
        migrations.AlterField(
            model_name='decodeimage',
            name='imag',
            field=models.ImageField(upload_to='decodeimg'),
        ),
    ]
