# Generated by Django 5.0.6 on 2024-06-30 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateapplication',
            name='job',
        ),
        migrations.RemoveField(
            model_name='candidateapplication',
            name='user',
        ),
        migrations.CreateModel(
            name='CandidateApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passingYear', models.IntegerField()),
                ('yearOfExp', models.IntegerField(default=0)),
                ('resume', models.FileField(upload_to='resume')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('selected', 'selected')], default='pending', max_length=20)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.jobpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='selectcandidatejob',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.candidateapplications'),
        ),
    ]
