# Generated by Django 5.0.6 on 2024-06-30 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_alter_myapplyjoblist_job'),
        ('hr', '0002_remove_candidateapplication_job_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidateApplication',
        ),
    ]
