# Generated by Django 5.1.3 on 2025-01-14 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateField()),
                ('publication_time', models.CharField(default='00:00', max_length=12)),
                ('imagename', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('imageurl', models.TextField(default='-')),
                ('catname', models.CharField(default='-', max_length=50)),
                ('catid', models.IntegerField(default=0)),
                ('ocatid', models.IntegerField(default=0)),
                ('show', models.IntegerField(default=0)),
                ('tag', models.TextField(default='')),
                ('act', models.IntegerField(default=0)),
                ('rand', models.IntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publication_date', '-id'],
            },
        ),
    ]
