# Generated by Django 5.1.3 on 2025-01-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('utxt', models.TextField()),
                ('email', models.TextField(default='')),
                ('ip', models.TextField(default='')),
                ('country', models.TextField(default='')),
            ],
        ),
    ]
