# Generated by Django 5.1.3 on 2024-12-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat',
            old_name='title',
            new_name='name',
        ),
    ]
