# Generated by Django 5.1.3 on 2024-12-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_rename_title_cat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='count',
            field=models.IntegerField(default='0'),
        ),
    ]
