# Generated by Django 5.1.3 on 2025-01-07 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trending', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Treding',
            new_name='Trending',
        ),
    ]
