# Generated by Django 5.1.3 on 2025-01-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_main_picname_main_picurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='picname',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='main',
            name='picurl',
            field=models.TextField(default=' '),
        ),
    ]
