# Generated by Django 5.1.3 on 2025-01-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_main_picname_alter_main_picurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='about',
            field=models.TextField(blank=True, max_length=900, null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='picname',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='picurl',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AlterField(
            model_name='main',
            name='set_name',
            field=models.TextField(default='-', null=True),
        ),
    ]
