# Generated by Django 5.1.3 on 2025-01-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_main_about_alter_main_picname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='picname2',
            field=models.TextField(default=' ', null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='picurl2',
            field=models.TextField(default=' ', null=True),
        ),
    ]
